# Generated by Django 4.0.1 on 2022-01-08 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileAdmin',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='ProfileSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
