# Generated by Django 4.0.1 on 2022-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_profile_profileadmin_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.AutoField(default=75369, primary_key=True, serialize=False),
        ),
    ]
