# Generated by Django 4.0.1 on 2022-01-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_id_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
