# Generated by Django 4.0.1 on 2022-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileadmin',
            options={'permissions': [('is_admin', 'Is Admin')]},
        ),
        migrations.AlterModelOptions(
            name='profileseller',
            options={'permissions': [('is_seller', 'Is Seller')]},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
